//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonKhayHoi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KonKhayHoiEntities : DbContext
    {
        public KonKhayHoiEntities()
            : base("name=KonKhayHoiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<Circulation> Circulation { get; set; }
        public virtual DbSet<Expenditure> Expenditure { get; set; }
        public virtual DbSet<Farm> Farm { get; set; }
        public virtual DbSet<last> last { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<Revenues> Revenues { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
    }
}
